###############################################################################
# group_vars/k8s_workers.yml
# Worker 노드 전용 변수
###############################################################################

node_role: worker
