###############################################################################
# group_vars/k8s_control_plane.yml
# Control Plane 노드 전용 변수
###############################################################################

# 첫 번째 CP (kubeadm init 실행 대상) — 나머지는 join
# inventory의 hosts 순서 영향 받지 않게 명시적으로 지정
primary_control_plane: k8s-cp1

# Control Plane 노드 role
node_role: control-plane
