#!/bin/sh

if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -Eq '^(package.json|pnpm-lock.yaml)$'; then
  pnpm install
fi

if git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD | grep -Eq '^(pyproject.toml|uv.lock)$'; then
  uv sync
fi
