site_name: Learning Project Docs
site_description: 개인/팀 학습용 문서 사이트
docs_dir: .
site_dir: ../site-learning
use_directory_urls: true

theme:
  name: material
  language: ko
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.copy

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
